name: jobs and workflows

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "this is step 1 of job 1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: echo "this is step 1 of job 2"
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: step3
        run: echo "this is step 1 of job 3"
  job4:
    runs-on: ubuntu-latest
    needs: [job2,job3]
    steps:
      - name: step4
        run: echo "this is step 1 of job 4"
