name: Step types

on:
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world!"
  say-hello-with-python-inline:
    runs-on: ubuntu-latest
    steps:
      - name: say hello with python
        run: python -c "print('hello world')"
  say-hello-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: say hello with action
        uses: actions/hello-world-javascript-action@v1
