name: Envionment Variables
on:
  workflow_dispatch:
env:
  GLOBAL_ENV_VAR: "I am a global environment variable"
jobs:
  env-var-job:
    runs-on: ubuntu-latest
    env:
      JOB_ENV_VAR: "I am a job environment variable"
    steps:
      - name: print environment variables
        env:
          STEP_ENV_VAR: "I am a step environment variable"
        run: |
          echo "Global env var: $GLOBAL_ENV_VAR"  
          echo "Job env var: $JOB_ENV_VAR"
          echo "Step env var: $STEP_ENV_VAR"
