name: Caching
on:
  workflow_dispatch:
jobs:
  generic-cache:
    name: generic cache with actions/cache
    runs-on: ubuntu-24.04
    steps:
      - name: restore cache
        id: demo-cache
        uses: actions/cache@v4
        with:
          name: demo-cache
          key: demo-cache-v1
      - name: populate cache directory
        if: steps.demo-cache.outputs.cache-hit != 'true'        
        run: |
          echo "Cache miss – generating contents"
          mkdir -p demo-cache
          date > demo-cache/timestamp.txt
      - name: save cache
        if: steps.demo-cache.outputs.cache-hit != 'true'  
        uses: actions/cache@v4
        with:
          name: demo-cache
          key: demo-cache-v1
