name: Runner types
on:
  workflow_dispatch:
jobs:
  github-hosted-ubuntu-vm:
    name: ubuntu-24.04 VM
    runs-on: ubuntu-24.04
    steps:
      - name: show the runner info
        run: |
          echo "Hello from ${{ runner.os }}"
          echo "Runner name (type): ${{ runner.name }}"
  github-hosted-windows-vm:
    name: windows-2022 VM
    runs-on: windows-2022
    steps:
      - name: show the runner info
        shell: pwsh
        run: |
          echo "Hello from ${{ runner.os }}"
          echo "Runner name (type): ${{ runner.name }}"
  github-hosted-macos-vm:
    name: macOS-14 VM
    runs-on: macos-14
    steps:
      - name: show the runner info
        run: |
          echo "Hello from ${{ runner.os }}"
          echo "Runner name (type): ${{ runner.name }}"
  github-hosted-alpine-container-on-ubuntu-vm:
      name: alpine container on ubuntu-24.04 VM
      runs-on: ubuntu-24.04
      container:
        image: alpine:3.20
      steps:
        - name: show the runner info
          run: |
            echo "Hello from ${{ runner.os }}"
            echo "Runner name (type): ${{ runner.name }}"
            echo "Container image:   $(grep PRETTY_NAME /etc/os-release)"
