name: Permissions
on:
  workflow_dispatch:
jobs:
  read-only-pr:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: list the first 5 prs
        run : gh pr list --limit 5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Attempt to add a label (expected to fail)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit 1 --add-label "documentation"
      - name: Confirm the failure
        if: failure()
        run: echo "❌  Write operation was blocked as expected – token is read-only."

  read-write-pr:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: add label to pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit 1 --add-label "documentation"
      - name: Confirm the
        if: success()
        run: echo "✅ Write operation succeeded!"


